In [2]:
import pandas as pd 
import numpy as np

In [88]:
df = pd.read_csv("prices_round_0_day_-1.csv", delimiter = ";")

In [108]:
df["profit_and_loss"] = 0.0 
df["day"] = -2
df = df.fillna("")

In [110]:
df

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-2,0,RAINFOREST_RESIN,10002,1,9996.0,2.0,9995.0,29.0,10004,2,10005.0,29.0,,,10003.0,0.0
1,-2,0,KELP,2028,1,2026.0,2.0,2025.0,29.0,2029,31,,,,,2028.5,0.0
2,-2,100,KELP,2025,24,,,,,2028,2,2029.0,22.0,,,2026.5,0.0
3,-2,100,RAINFOREST_RESIN,9996,2,9995.0,22.0,,,10004,2,10005.0,22.0,,,10000.0,0.0
4,-2,200,RAINFOREST_RESIN,9995,20,,,,,10005,20,,,,,10000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,-2,199700,KELP,2020,27,,,,,2023,2,2024.0,25.0,,,2021.5,0.0
3996,-2,199800,RAINFOREST_RESIN,9995,21,,,,,10002,8,10005.0,21.0,,,9998.5,0.0
3997,-2,199800,KELP,2020,21,,,,,2023,21,,,,,2021.5,0.0
3998,-2,199900,KELP,2020,32,,,,,2022,7,2023.0,2.0,2024.0,30.0,2021.0,0.0
3999,-2,199900,RAINFOREST_RESIN,9996,2,9995.0,30.0,,,10004,2,10005.0,30.0,,,10000.0,0.0

In [112]:
df_single = df.astype(str).agg(";".join, axis=1).to_frame(name="merged")

In [114]:

data_rows = df.astype(str).agg(";".join, axis=1)

# Convert header to a string
header_row = ";".join(df.columns)

# Combine header and data into one list
all_rows = [header_row] + data_rows.tolist()

# Save to CSV (4000x1 style with semicolon delimiter)
with open("output.csv", "w") as f:
    for row in all_rows:
        f.write(row + "\n")

In [104]:
#df_single.to_csv("output.csv", index=False)